version: '3.8'

services:
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
  postgres:
    ports:
      - '5432:5432'
  nextjs:
    ports:
      - '3000:3000'
  redis:
    ports:
      - '6379:6379'
